package com.studio.vuepage.export;

import com.studio.vuepage.dsl.model.DslNode;
import com.studio.vuepage.dsl.model.PageDsl;

import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Element Plus 风格 Vue 3 SFC 拼装。
 */
final class ElementPlusSfcBuilder {

    private final StringBuilder template = new StringBuilder();
    private final StringBuilder scriptBody = new StringBuilder();
    private final AtomicInteger mockSeed = new AtomicInteger(0);
    private boolean needReactive;

    String build(PageDsl dsl) {
        needReactive = false;
        template.setLength(0);
        scriptBody.setLength(0);

        template.append("  <div class=\"page-studio\">\n");
        if (dsl.getChildren() != null) {
            for (DslNode child : dsl.getChildren()) {
                renderNode(child, 2);
            }
        }
        template.append("  </div>\n");

        StringBuilder sfc = new StringBuilder();
        sfc.append("<!--\n");
        sfc.append("  Generated by VuePage Studio.\n");
        sfc.append("  Style: element-plus. Host project must install and register Element Plus.\n");
        sfc.append("  Page title: ").append(HtmlEscaper.escapeText(dsl.getTitle())).append("\n");
        sfc.append("-->\n");
        sfc.append("<template>\n");
        sfc.append(template);
        sfc.append("</template>\n\n");
        sfc.append("<script setup>\n");
        if (needReactive) {
            sfc.append("import { reactive } from 'vue'\n\n");
        }
        sfc.append(scriptBody);
        sfc.append("</script>\n\n");
        sfc.append("<style scoped>\n");
        sfc.append(".page-studio { padding: 16px; display: flex; flex-direction: column; gap: 16px; }\n");
        sfc.append(".page-header { display: flex; align-items: center; justify-content: space-between; gap: 12px; }\n");
        sfc.append(".page-header h1 { margin: 0; font-size: 20px; font-weight: 600; }\n");
        sfc.append(".page-header__actions { display: flex; gap: 8px; }\n");
        sfc.append(".stat-cards { display: grid; grid-template-columns: repeat(auto-fill, minmax(160px, 1fr)); gap: 12px; }\n");
        sfc.append(".stat-card__value { font-size: 24px; font-weight: 600; }\n");
        sfc.append(".stat-card__label { color: #666; font-size: 13px; margin-top: 4px; }\n");
        sfc.append(".container-stack { display: flex; flex-direction: column; gap: 16px; }\n");
        sfc.append(".container-two-column { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }\n");
        sfc.append(".table-actions { display: flex; gap: 8px; }\n");
        sfc.append(".pagination-wrap { display: flex; justify-content: flex-end; }\n");
        sfc.append(".text-block { color: #333; line-height: 1.6; }\n");
        sfc.append(".text-block--hint { color: #909399; font-size: 13px; }\n");
        sfc.append(".action-bar { display: flex; gap: 8px; }\n");
        sfc.append("</style>\n");
        return sfc.toString();
    }

    private void renderNode(DslNode node, int indent) {
        if (node == null || node.getType() == null) {
            return;
        }
        switch (node.getType()) {
            case "PageHeader" -> renderPageHeader(node, indent);
            case "Breadcrumb" -> renderBreadcrumb(node, indent);
            case "AlertBanner" -> renderAlert(node, indent);
            case "SearchBar" -> renderSearchBar(node, indent);
            case "DataTable" -> renderDataTable(node, indent);
            case "Pagination" -> renderPagination(node, indent);
            case "FormSection" -> renderFormSection(node, indent);
            case "DescriptionList" -> renderDescriptions(node, indent);
            case "ActionBar" -> renderActionBar(node, indent);
            case "StatCards" -> renderStatCards(node, indent);
            case "Tabs" -> renderTabs(node, indent);
            case "Steps" -> renderSteps(node, indent);
            case "Timeline" -> renderTimeline(node, indent);
            case "TagGroup" -> renderTags(node, indent);
            case "TreeNav" -> renderTree(node, indent);
            case "EmptyState" -> renderEmpty(node, indent);
            case "ResultBlock" -> renderResult(node, indent);
            case "ImageBlock" -> renderImage(node, indent);
            case "Divider" -> renderDivider(node, indent);
            case "TextBlock" -> renderTextBlock(node, indent);
            case "Container" -> renderContainer(node, indent);
            default -> {
                // 忽略未知类型（校验阶段已拦截）
            }
        }
    }

    private void renderBreadcrumb(DslNode node, int indent) {
        List<Map<String, Object>> items = SfcBuildSupport.listOfMaps(node.getProps().get("items"));
        indent(indent).append("<el-breadcrumb separator=\"/\">\n");
        for (Map<String, Object> it : items) {
            indent(indent + 1)
                    .append("<el-breadcrumb-item>")
                    .append(HtmlEscaper.escapeText(SfcBuildSupport.str(it.get("label"))))
                    .append("</el-breadcrumb-item>\n");
        }
        indent(indent).append("</el-breadcrumb>\n");
    }

    private void renderAlert(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        String type = SfcBuildSupport.propString(props, "type", "info");
        String title = HtmlEscaper.escapeText(SfcBuildSupport.propString(props, "title", ""));
        String desc = HtmlEscaper.escapeText(SfcBuildSupport.propString(props, "description", ""));
        boolean closable = Boolean.TRUE.equals(props.get("closable"));
        indent(indent)
                .append("<el-alert title=\"")
                .append(HtmlEscaper.escapeAttr(title))
                .append("\" type=\"")
                .append(HtmlEscaper.escapeAttr(type))
                .append("\" description=\"")
                .append(HtmlEscaper.escapeAttr(desc))
                .append("\" ")
                .append(closable ? "closable" : ":closable=\"false\"")
                .append(" show-icon />\n");
    }

    private void renderDescriptions(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        int column = 2;
        Object col = props.get("column");
        if (col instanceof Number n) {
            column = Math.max(1, n.intValue());
        }
        List<Map<String, Object>> items = SfcBuildSupport.listOfMaps(props.get("items"));
        indent(indent).append("<el-descriptions :column=\"").append(column).append("\" border>\n");
        for (Map<String, Object> it : items) {
            indent(indent + 1)
                    .append("<el-descriptions-item label=\"")
                    .append(HtmlEscaper.escapeAttr(SfcBuildSupport.str(it.get("label"))))
                    .append("\">")
                    .append(HtmlEscaper.escapeText(SfcBuildSupport.str(it.get("value"))))
                    .append("</el-descriptions-item>\n");
        }
        indent(indent).append("</el-descriptions>\n");
    }

    private void renderTabs(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        String active = SfcBuildSupport.propString(props, "active", "tab1");
        List<Map<String, Object>> items = SfcBuildSupport.listOfMaps(props.get("items"));
        indent(indent).append("<el-tabs model-value=\"").append(HtmlEscaper.escapeAttr(active)).append("\">\n");
        for (Map<String, Object> it : items) {
            String name = SfcBuildSupport.str(it.get("name"));
            if (name.isBlank()) {
                name = SfcBuildSupport.str(it.get("id"));
            }
            indent(indent + 1)
                    .append("<el-tab-pane label=\"")
                    .append(HtmlEscaper.escapeAttr(SfcBuildSupport.str(it.get("label"))))
                    .append("\" name=\"")
                    .append(HtmlEscaper.escapeAttr(name))
                    .append("\">")
                    .append(HtmlEscaper.escapeText(SfcBuildSupport.str(it.get("label"))))
                    .append(" 内容</el-tab-pane>\n");
        }
        indent(indent).append("</el-tabs>\n");
    }

    private void renderSteps(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        int active = 0;
        Object a = props.get("active");
        if (a instanceof Number n) {
            active = n.intValue();
        }
        List<Map<String, Object>> items = SfcBuildSupport.listOfMaps(props.get("items"));
        indent(indent).append("<el-steps :active=\"").append(active).append("\" finish-status=\"success\">\n");
        for (Map<String, Object> it : items) {
            indent(indent + 1)
                    .append("<el-step title=\"")
                    .append(HtmlEscaper.escapeAttr(SfcBuildSupport.str(it.get("title"))))
                    .append("\" description=\"")
                    .append(HtmlEscaper.escapeAttr(SfcBuildSupport.str(it.get("description"))))
                    .append("\" />\n");
        }
        indent(indent).append("</el-steps>\n");
    }

    private void renderTimeline(DslNode node, int indent) {
        List<Map<String, Object>> items = SfcBuildSupport.listOfMaps(node.getProps().get("items"));
        indent(indent).append("<el-timeline>\n");
        for (Map<String, Object> it : items) {
            indent(indent + 1)
                    .append("<el-timeline-item timestamp=\"")
                    .append(HtmlEscaper.escapeAttr(SfcBuildSupport.str(it.get("timestamp"))))
                    .append("\">")
                    .append(HtmlEscaper.escapeText(SfcBuildSupport.str(it.get("content"))))
                    .append("</el-timeline-item>\n");
        }
        indent(indent).append("</el-timeline>\n");
    }

    private void renderTags(DslNode node, int indent) {
        List<Map<String, Object>> tags = SfcBuildSupport.listOfMaps(node.getProps().get("tags"));
        indent(indent).append("<div class=\"tag-group\">\n");
        for (Map<String, Object> t : tags) {
            String type = SfcBuildSupport.str(t.get("type"));
            indent(indent + 1).append("<el-tag");
            if (!type.isBlank()) {
                template.append(" type=\"").append(HtmlEscaper.escapeAttr(type)).append("\"");
            }
            template
                    .append(" style=\"margin-right: 8px\">")
                    .append(HtmlEscaper.escapeText(SfcBuildSupport.str(t.get("label"))))
                    .append("</el-tag>\n");
        }
        indent(indent).append("</div>\n");
    }

    private void renderTree(DslNode node, int indent) {
        // 使用静态 data 常量，避免复杂交互
        String var = "treeData_" + SfcBuildSupport.safeJsId(node.getId());
        scriptBody.append("const ").append(var).append(" = ")
                .append(toJsArray(node.getProps().get("data")))
                .append("\n");
        indent(indent)
                .append("<el-tree :data=\"")
                .append(var)
                .append("\" :props=\"{ label: 'label', children: 'children' }\" default-expand-all />\n");
    }

    private void renderEmpty(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        indent(indent)
                .append("<el-empty description=\"")
                .append(HtmlEscaper.escapeAttr(SfcBuildSupport.propString(props, "title", "暂无数据")))
                .append("\">\n");
        String desc = SfcBuildSupport.propString(props, "description", "");
        if (!desc.isBlank()) {
            indent(indent + 1).append("<p>").append(HtmlEscaper.escapeText(desc)).append("</p>\n");
        }
        indent(indent).append("</el-empty>\n");
    }

    private void renderResult(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        indent(indent)
                .append("<el-result icon=\"")
                .append(HtmlEscaper.escapeAttr(SfcBuildSupport.propString(props, "status", "success")))
                .append("\" title=\"")
                .append(HtmlEscaper.escapeAttr(SfcBuildSupport.propString(props, "title", "")))
                .append("\" sub-title=\"")
                .append(HtmlEscaper.escapeAttr(SfcBuildSupport.propString(props, "subTitle", "")))
                .append("\" />\n");
    }

    private void renderImage(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        indent(indent)
                .append("<el-image src=\"")
                .append(HtmlEscaper.escapeAttr(SfcBuildSupport.propString(props, "src", "")))
                .append("\" alt=\"")
                .append(HtmlEscaper.escapeAttr(SfcBuildSupport.propString(props, "alt", "")))
                .append("\" fit=\"")
                .append(HtmlEscaper.escapeAttr(SfcBuildSupport.propString(props, "fit", "cover")))
                .append("\" style=\"width: 100%; max-height: 240px\" />\n");
    }

    private void renderDivider(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        String content = SfcBuildSupport.propString(props, "content", "");
        String pos = SfcBuildSupport.propString(props, "contentPosition", "center");
        if (content.isBlank()) {
            indent(indent).append("<el-divider />\n");
        } else {
            indent(indent)
                    .append("<el-divider content-position=\"")
                    .append(HtmlEscaper.escapeAttr(pos))
                    .append("\">")
                    .append(HtmlEscaper.escapeText(content))
                    .append("</el-divider>\n");
        }
    }

    /** 将 list/map 结构粗略序列化为 JS 字面量（仅用于 tree mock） */
    private String toJsArray(Object value) {
        if (!(value instanceof List<?> list)) {
            return "[]";
        }
        StringBuilder sb = new StringBuilder("[");
        for (int i = 0; i < list.size(); i++) {
            if (i > 0) {
                sb.append(',');
            }
            Object item = list.get(i);
            if (item instanceof Map<?, ?> map) {
                sb.append('{');
                int j = 0;
                for (Map.Entry<?, ?> e : map.entrySet()) {
                    if (j++ > 0) {
                        sb.append(',');
                    }
                    String key = String.valueOf(e.getKey());
                    sb.append(SfcBuildSupport.safeJsId(key)).append(':');
                    Object v = e.getValue();
                    if (v instanceof List<?>) {
                        sb.append(toJsArray(v));
                    } else if (v instanceof Number || v instanceof Boolean) {
                        sb.append(v);
                    } else {
                        sb.append(SfcBuildSupport.jsString(String.valueOf(v == null ? "" : v)));
                    }
                }
                sb.append('}');
            }
        }
        sb.append(']');
        return sb.toString();
    }

    private void renderPageHeader(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        String title = HtmlEscaper.escapeText(SfcBuildSupport.propString(props, "title", ""));
        List<Map<String, Object>> actions = SfcBuildSupport.listOfMaps(props.get("actions"));

        indent(indent).append("<div class=\"page-header\">\n");
        indent(indent + 1).append("<h1>").append(title).append("</h1>\n");
        if (!actions.isEmpty()) {
            indent(indent + 1).append("<div class=\"page-header__actions\">\n");
            for (Map<String, Object> act : actions) {
                String label = HtmlEscaper.escapeText(SfcBuildSupport.str(act.get("label")));
                String type = SfcBuildSupport.str(act.get("type"));
                if (type.isBlank()) {
                    type = "default";
                }
                indent(indent + 2)
                        .append("<el-button type=\"")
                        .append(HtmlEscaper.escapeAttr(type))
                        .append("\">")
                        .append(label)
                        .append("</el-button>\n");
            }
            indent(indent + 1).append("</div>\n");
        }
        indent(indent).append("</div>\n");
    }

    private void renderSearchBar(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        List<Map<String, Object>> fields = SfcBuildSupport.listOfMaps(props.get("fields"));
        String formVar = "searchForm_" + SfcBuildSupport.safeJsId(node.getId());

        needReactive = true;
        scriptBody.append("// search form: ").append(node.getId()).append("\n");
        scriptBody.append("const ").append(formVar).append(" = reactive({\n");
        for (int i = 0; i < fields.size(); i++) {
            String name = SfcBuildSupport.str(fields.get(i).get("name"));
            if (name.isBlank()) {
                continue;
            }
            scriptBody.append("  ").append(name).append(": ''");
            if (i < fields.size() - 1) {
                scriptBody.append(",");
            }
            scriptBody.append("\n");
        }
        scriptBody.append("})\n\n");

        indent(indent).append("<el-form :inline=\"true\" :model=\"").append(formVar).append("\" class=\"search-bar\">\n");
        for (Map<String, Object> field : fields) {
            String name = SfcBuildSupport.str(field.get("name"));
            String label = HtmlEscaper.escapeAttr(SfcBuildSupport.str(field.get("label")));
            String control = SfcBuildSupport.str(field.get("control"));
            indent(indent + 1).append("<el-form-item label=\"").append(label).append("\">\n");
            if ("select".equals(control)) {
                indent(indent + 2)
                        .append("<el-select v-model=\"")
                        .append(formVar).append(".").append(name)
                        .append("\" clearable placeholder=\"请选择\">\n");
                Object rawOpts = field.get("options");
                if (rawOpts instanceof List<?> list) {
                    for (Object opt : list) {
                        String optVal = HtmlEscaper.escapeAttr(SfcBuildSupport.str(opt));
                        indent(indent + 3)
                                .append("<el-option label=\"")
                                .append(optVal)
                                .append("\" value=\"")
                                .append(optVal)
                                .append("\" />\n");
                    }
                }
                indent(indent + 2).append("</el-select>\n");
            } else {
                indent(indent + 2)
                        .append("<el-input v-model=\"")
                        .append(formVar).append(".").append(name)
                        .append("\" clearable placeholder=\"请输入\" />\n");
            }
            indent(indent + 1).append("</el-form-item>\n");
        }
        indent(indent + 1).append("<el-form-item>\n");
        indent(indent + 2).append("<el-button type=\"primary\">查询</el-button>\n");
        indent(indent + 2).append("<el-button>重置</el-button>\n");
        indent(indent + 1).append("</el-form-item>\n");
        indent(indent).append("</el-form>\n");
    }

    private void renderDataTable(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        List<Map<String, Object>> columns = SfcBuildSupport.listOfMaps(props.get("columns"));
        List<Map<String, Object>> rowActions = SfcBuildSupport.listOfMaps(props.get("rowActions"));
        String dataVar = "tableData_" + SfcBuildSupport.safeJsId(node.getId());

        scriptBody.append("// mock table data: ").append(node.getId()).append("\n");
        scriptBody.append("const ").append(dataVar).append(" = [\n  ");
        scriptBody.append(SfcBuildSupport.buildMockRowsJs(columns, mockSeed));
        scriptBody.append("\n]\n\n");

        indent(indent).append("<el-table :data=\"").append(dataVar).append("\" stripe border style=\"width: 100%\">\n");
        for (Map<String, Object> col : columns) {
            String prop = HtmlEscaper.escapeAttr(SfcBuildSupport.str(col.get("prop")));
            String label = HtmlEscaper.escapeAttr(SfcBuildSupport.str(col.get("label")));
            indent(indent + 1)
                    .append("<el-table-column prop=\"")
                    .append(prop)
                    .append("\" label=\"")
                    .append(label)
                    .append("\"");
            Object width = col.get("width");
            if (width instanceof Number) {
                indent(0); // no-op keep style
                template.append(" width=\"").append(width).append("\"");
            }
            template.append(" />\n");
        }
        if (!rowActions.isEmpty()) {
            indent(indent + 1).append("<el-table-column label=\"操作\" fixed=\"right\" width=\"160\">\n");
            indent(indent + 2).append("<template #default>\n");
            indent(indent + 3).append("<div class=\"table-actions\">\n");
            for (Map<String, Object> act : rowActions) {
                String label = HtmlEscaper.escapeText(SfcBuildSupport.str(act.get("label")));
                indent(indent + 4)
                        .append("<el-button link type=\"primary\">")
                        .append(label)
                        .append("</el-button>\n");
            }
            indent(indent + 3).append("</div>\n");
            indent(indent + 2).append("</template>\n");
            indent(indent + 1).append("</el-table-column>\n");
        }
        indent(indent).append("</el-table>\n");
    }

    private void renderPagination(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        int pageSize = SfcBuildSupport.propInt(props, "pageSize", 10);
        // UI only
        indent(indent).append("<div class=\"pagination-wrap\">\n");
        indent(indent + 1)
                .append("<el-pagination background layout=\"total, prev, pager, next\" :page-size=\"")
                .append(pageSize)
                .append("\" :total=\"3\" />\n");
        indent(indent).append("</div>\n");
    }

    private void renderFormSection(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        List<Map<String, Object>> fields = SfcBuildSupport.listOfMaps(props.get("fields"));
        String formVar = "form_" + SfcBuildSupport.safeJsId(node.getId());
        String submitFn = "onSubmit_" + SfcBuildSupport.safeJsId(node.getId());

        needReactive = true;
        scriptBody.append("// form model: ").append(node.getId()).append("\n");
        scriptBody.append("const ").append(formVar).append(" = reactive({\n");
        for (int i = 0; i < fields.size(); i++) {
            String name = SfcBuildSupport.str(fields.get(i).get("name"));
            if (name.isBlank()) {
                continue;
            }
            scriptBody.append("  ").append(name).append(": ''");
            if (i < fields.size() - 1) {
                scriptBody.append(",");
            }
            scriptBody.append("\n");
        }
        scriptBody.append("})\n\n");
        scriptBody.append("function ").append(submitFn).append("() {\n");
        scriptBody.append("  console.log('submit', ").append(formVar).append(")\n");
        scriptBody.append("}\n\n");

        // 供同页 ActionBar 调用：暴露最后一个 form 的 submit（ActionBar 通过全局约定）
        scriptBody.append("// expose for ActionBar stubs\n");
        scriptBody.append("const __lastFormSubmit = ").append(submitFn).append("\n\n");

        indent(indent).append("<el-form :model=\"").append(formVar).append("\" label-width=\"100px\" class=\"form-section\">\n");
        for (Map<String, Object> field : fields) {
            String name = SfcBuildSupport.str(field.get("name"));
            String label = HtmlEscaper.escapeAttr(SfcBuildSupport.str(field.get("label")));
            String control = SfcBuildSupport.str(field.get("control"));
            boolean required = Boolean.TRUE.equals(field.get("required"));
            boolean readonly = Boolean.TRUE.equals(field.get("readonly"));

            indent(indent + 1)
                    .append("<el-form-item label=\"")
                    .append(label)
                    .append("\"");
            if (required) {
                template.append(" required");
            }
            template.append(">\n");

            if ("textarea".equals(control)) {
                indent(indent + 2)
                        .append("<el-input v-model=\"")
                        .append(formVar).append(".").append(name)
                        .append("\" type=\"textarea\" rows=\"3\"");
                if (readonly) {
                    template.append(" readonly");
                }
                template.append(" />\n");
            } else if ("select".equals(control)) {
                indent(indent + 2)
                        .append("<el-select v-model=\"")
                        .append(formVar).append(".").append(name)
                        .append("\" clearable");
                if (readonly) {
                    template.append(" disabled");
                }
                template.append(">\n");
                Object rawOpts = field.get("options");
                if (rawOpts instanceof List<?> list) {
                    for (Object opt : list) {
                        String optVal = HtmlEscaper.escapeAttr(SfcBuildSupport.str(opt));
                        indent(indent + 3)
                                .append("<el-option label=\"")
                                .append(optVal)
                                .append("\" value=\"")
                                .append(optVal)
                                .append("\" />\n");
                    }
                }
                indent(indent + 2).append("</el-select>\n");
            } else {
                indent(indent + 2)
                        .append("<el-input v-model=\"")
                        .append(formVar).append(".").append(name)
                        .append("\"");
                if (readonly) {
                    template.append(" readonly");
                }
                template.append(" />\n");
            }
            indent(indent + 1).append("</el-form-item>\n");
        }
        indent(indent).append("</el-form>\n");
    }

    private void renderActionBar(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        List<Map<String, Object>> actions = SfcBuildSupport.listOfMaps(props.get("actions"));
        String handler = "onAction_" + SfcBuildSupport.safeJsId(node.getId());

        scriptBody.append("function ").append(handler).append("(actionId) {\n");
        scriptBody.append("  if (typeof __lastFormSubmit === 'function' && (actionId === 'act_submit' || actionId === 'submit')) {\n");
        scriptBody.append("    __lastFormSubmit()\n");
        scriptBody.append("    return\n");
        scriptBody.append("  }\n");
        scriptBody.append("  console.log('action', actionId)\n");
        scriptBody.append("}\n\n");

        indent(indent).append("<div class=\"action-bar\">\n");
        for (Map<String, Object> act : actions) {
            String id = SfcBuildSupport.str(act.get("id"));
            String label = HtmlEscaper.escapeText(SfcBuildSupport.str(act.get("label")));
            String type = SfcBuildSupport.str(act.get("type"));
            if (type.isBlank()) {
                type = "default";
            }
            indent(indent + 1)
                    .append("<el-button type=\"")
                    .append(HtmlEscaper.escapeAttr(type))
                    .append("\" @click=\"")
                    .append(handler)
                    .append("(")
                    .append(SfcBuildSupport.jsString(id))
                    .append(")\">")
                    .append(label)
                    .append("</el-button>\n");
        }
        indent(indent).append("</div>\n");
    }

    private void renderStatCards(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        List<Map<String, Object>> items = SfcBuildSupport.listOfMaps(props.get("items"));

        indent(indent).append("<div class=\"stat-cards\">\n");
        for (Map<String, Object> item : items) {
            String label = HtmlEscaper.escapeText(SfcBuildSupport.str(item.get("label")));
            String value = HtmlEscaper.escapeText(SfcBuildSupport.str(item.get("value")));
            String unit = HtmlEscaper.escapeText(SfcBuildSupport.str(item.get("unit")));
            indent(indent + 1).append("<el-card shadow=\"hover\" class=\"stat-card\">\n");
            indent(indent + 2).append("<div class=\"stat-card__value\">").append(value);
            if (!unit.isBlank()) {
                template.append("<span class=\"stat-card__unit\">").append(unit).append("</span>");
            }
            template.append("</div>\n");
            indent(indent + 2).append("<div class=\"stat-card__label\">").append(label).append("</div>\n");
            indent(indent + 1).append("</el-card>\n");
        }
        indent(indent).append("</div>\n");
    }

    private void renderTextBlock(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        String content = HtmlEscaper.escapeText(SfcBuildSupport.propString(props, "content", ""));
        String variant = SfcBuildSupport.propString(props, "variant", "body");
        String cls = "hint".equals(variant) ? "text-block text-block--hint" : "text-block";
        indent(indent).append("<p class=\"").append(cls).append("\">").append(content).append("</p>\n");
    }

    private void renderContainer(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        String layout = SfcBuildSupport.propString(props, "layout", "stack");
        if ("two-column".equals(layout)) {
            List<DslNode> left = SfcBuildSupport.asNodes(props.get("left"));
            List<DslNode> right = SfcBuildSupport.asNodes(props.get("right"));
            indent(indent).append("<div class=\"container-two-column\">\n");
            indent(indent + 1).append("<div class=\"container-col\">\n");
            for (DslNode child : left) {
                renderNode(child, indent + 2);
            }
            indent(indent + 1).append("</div>\n");
            indent(indent + 1).append("<div class=\"container-col\">\n");
            for (DslNode child : right) {
                renderNode(child, indent + 2);
            }
            indent(indent + 1).append("</div>\n");
            indent(indent).append("</div>\n");
        } else {
            indent(indent).append("<div class=\"container-stack\">\n");
            if (node.getChildren() != null) {
                for (DslNode child : node.getChildren()) {
                    renderNode(child, indent + 1);
                }
            }
            indent(indent).append("</div>\n");
        }
    }

    private StringBuilder indent(int level) {
        SfcBuildSupport.appendIndent(template, level);
        return template;
    }
}
