package com.studio.vuepage.export;

import com.studio.vuepage.dsl.model.DslNode;
import com.studio.vuepage.dsl.model.PageDsl;

import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * plain 风格：语义化 HTML + scoped CSS。
 */
final class PlainSfcBuilder {

    private final StringBuilder template = new StringBuilder();
    private final StringBuilder scriptBody = new StringBuilder();
    private final AtomicInteger mockSeed = new AtomicInteger(0);
    private boolean needReactive;

    String build(PageDsl dsl) {
        needReactive = false;
        template.setLength(0);
        scriptBody.setLength(0);

        template.append("  <div class=\"page-studio page-studio--plain\">\n");
        if (dsl.getChildren() != null) {
            for (DslNode child : dsl.getChildren()) {
                renderNode(child, 2);
            }
        }
        template.append("  </div>\n");

        StringBuilder sfc = new StringBuilder();
        sfc.append("<!--\n");
        sfc.append("  Generated by VuePage Studio.\n");
        sfc.append("  Style: plain (semantic HTML + scoped CSS).\n");
        sfc.append("  Page title: ").append(HtmlEscaper.escapeText(dsl.getTitle())).append("\n");
        sfc.append("-->\n");
        sfc.append("<template>\n");
        sfc.append(template);
        sfc.append("</template>\n\n");
        sfc.append("<script setup>\n");
        if (needReactive) {
            sfc.append("import { reactive } from 'vue'\n\n");
        }
        sfc.append(scriptBody);
        sfc.append("</script>\n\n");
        sfc.append("<style scoped>\n");
        sfc.append(".page-studio--plain { padding: 16px; display: flex; flex-direction: column; gap: 16px; font-family: system-ui, sans-serif; color: #303133; }\n");
        sfc.append(".page-header { display: flex; align-items: center; justify-content: space-between; gap: 12px; }\n");
        sfc.append(".page-header h1 { margin: 0; font-size: 20px; font-weight: 600; }\n");
        sfc.append(".page-header__actions { display: flex; gap: 8px; }\n");
        sfc.append(".btn { display: inline-flex; align-items: center; padding: 6px 14px; border: 1px solid #dcdfe6; border-radius: 4px; background: #fff; cursor: pointer; font-size: 14px; }\n");
        sfc.append(".btn--primary { background: #409eff; border-color: #409eff; color: #fff; }\n");
        sfc.append(".btn--danger { background: #f56c6c; border-color: #f56c6c; color: #fff; }\n");
        sfc.append(".btn--link { border: none; background: transparent; color: #409eff; padding: 0 4px; }\n");
        sfc.append(".search-bar { display: flex; flex-wrap: wrap; gap: 12px; align-items: flex-end; }\n");
        sfc.append(".field { display: flex; flex-direction: column; gap: 4px; }\n");
        sfc.append(".field label { font-size: 13px; color: #606266; }\n");
        sfc.append(".field input, .field select, .field textarea { min-width: 160px; padding: 6px 10px; border: 1px solid #dcdfe6; border-radius: 4px; }\n");
        sfc.append("table.data-table { width: 100%; border-collapse: collapse; }\n");
        sfc.append("table.data-table th, table.data-table td { border: 1px solid #ebeef5; padding: 8px 12px; text-align: left; }\n");
        sfc.append("table.data-table th { background: #f5f7fa; }\n");
        sfc.append(".pagination { display: flex; justify-content: flex-end; gap: 8px; align-items: center; font-size: 13px; color: #606266; }\n");
        sfc.append(".form-section { display: flex; flex-direction: column; gap: 12px; max-width: 480px; }\n");
        sfc.append(".action-bar { display: flex; gap: 8px; }\n");
        sfc.append(".stat-cards { display: grid; grid-template-columns: repeat(auto-fill, minmax(160px, 1fr)); gap: 12px; }\n");
        sfc.append(".stat-card { border: 1px solid #ebeef5; border-radius: 8px; padding: 16px; background: #fff; }\n");
        sfc.append(".stat-card__value { font-size: 24px; font-weight: 600; }\n");
        sfc.append(".stat-card__label { color: #666; font-size: 13px; margin-top: 4px; }\n");
        sfc.append(".container-stack { display: flex; flex-direction: column; gap: 16px; }\n");
        sfc.append(".container-two-column { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }\n");
        sfc.append(".text-block { line-height: 1.6; }\n");
        sfc.append(".text-block--hint { color: #909399; font-size: 13px; }\n");
        sfc.append("</style>\n");
        return sfc.toString();
    }

    private void renderNode(DslNode node, int indent) {
        if (node == null || node.getType() == null) {
            return;
        }
        switch (node.getType()) {
            case "PageHeader" -> renderPageHeader(node, indent);
            case "Breadcrumb" -> renderSimpleList(node, indent, "items", "label", "nav", " / ");
            case "AlertBanner" -> {
                Map<String, Object> p = node.getProps();
                indent(indent).append("<div class=\"alert alert--")
                        .append(HtmlEscaper.escapeAttr(SfcBuildSupport.propString(p, "type", "info")))
                        .append("\"><strong>")
                        .append(HtmlEscaper.escapeText(SfcBuildSupport.propString(p, "title", "")))
                        .append("</strong> ")
                        .append(HtmlEscaper.escapeText(SfcBuildSupport.propString(p, "description", "")))
                        .append("</div>\n");
            }
            case "SearchBar" -> renderSearchBar(node, indent);
            case "DataTable" -> renderDataTable(node, indent);
            case "Pagination" -> renderPagination(node, indent);
            case "FormSection" -> renderFormSection(node, indent);
            case "DescriptionList" -> {
                indent(indent).append("<dl class=\"desc-list\">\n");
                for (Map<String, Object> it : SfcBuildSupport.listOfMaps(node.getProps().get("items"))) {
                    indent(indent + 1).append("<div><dt>")
                            .append(HtmlEscaper.escapeText(SfcBuildSupport.str(it.get("label"))))
                            .append("</dt><dd>")
                            .append(HtmlEscaper.escapeText(SfcBuildSupport.str(it.get("value"))))
                            .append("</dd></div>\n");
                }
                indent(indent).append("</dl>\n");
            }
            case "ActionBar" -> renderActionBar(node, indent);
            case "StatCards" -> renderStatCards(node, indent);
            case "Tabs", "Steps", "Timeline", "TagGroup" -> renderSimpleList(
                    node, indent,
                    node.getType().equals("TagGroup") ? "tags" : "items",
                    node.getType().equals("Steps") ? "title" : (node.getType().equals("Timeline") ? "content" : "label"),
                    "plain-list",
                    " · "
            );
            case "TreeNav" -> {
                indent(indent).append("<ul class=\"tree\">\n");
                for (Map<String, Object> it : SfcBuildSupport.listOfMaps(node.getProps().get("data"))) {
                    indent(indent + 1).append("<li>")
                            .append(HtmlEscaper.escapeText(SfcBuildSupport.str(it.get("label"))))
                            .append("</li>\n");
                }
                indent(indent).append("</ul>\n");
            }
            case "EmptyState" -> indent(indent).append("<div class=\"empty\"><h3>")
                    .append(HtmlEscaper.escapeText(SfcBuildSupport.propString(node.getProps(), "title", "暂无数据")))
                    .append("</h3><p>")
                    .append(HtmlEscaper.escapeText(SfcBuildSupport.propString(node.getProps(), "description", "")))
                    .append("</p></div>\n");
            case "ResultBlock" -> indent(indent).append("<div class=\"result\"><h2>")
                    .append(HtmlEscaper.escapeText(SfcBuildSupport.propString(node.getProps(), "title", "")))
                    .append("</h2><p>")
                    .append(HtmlEscaper.escapeText(SfcBuildSupport.propString(node.getProps(), "subTitle", "")))
                    .append("</p></div>\n");
            case "ImageBlock" -> indent(indent).append("<img class=\"img-block\" src=\"")
                    .append(HtmlEscaper.escapeAttr(SfcBuildSupport.propString(node.getProps(), "src", "")))
                    .append("\" alt=\"")
                    .append(HtmlEscaper.escapeAttr(SfcBuildSupport.propString(node.getProps(), "alt", "")))
                    .append("\" />\n");
            case "Divider" -> {
                String c = SfcBuildSupport.propString(node.getProps(), "content", "");
                if (c.isBlank()) {
                    indent(indent).append("<hr class=\"divider\" />\n");
                } else {
                    indent(indent).append("<div class=\"divider-text\">")
                            .append(HtmlEscaper.escapeText(c)).append("</div>\n");
                }
            }
            case "TextBlock" -> renderTextBlock(node, indent);
            case "Container" -> renderContainer(node, indent);
            default -> {
            }
        }
    }

    private void renderSimpleList(
            DslNode node,
            int indent,
            String listKey,
            String labelKey,
            String cssClass,
            String sep
    ) {
        List<Map<String, Object>> items = SfcBuildSupport.listOfMaps(node.getProps().get(listKey));
        indent(indent).append("<div class=\"").append(cssClass).append("\">");
        for (int i = 0; i < items.size(); i++) {
            if (i > 0) {
                template.append(HtmlEscaper.escapeText(sep));
            }
            template.append(HtmlEscaper.escapeText(SfcBuildSupport.str(items.get(i).get(labelKey))));
        }
        template.append("</div>\n");
    }

    private void renderPageHeader(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        String title = HtmlEscaper.escapeText(SfcBuildSupport.propString(props, "title", ""));
        List<Map<String, Object>> actions = SfcBuildSupport.listOfMaps(props.get("actions"));

        indent(indent).append("<header class=\"page-header\">\n");
        indent(indent + 1).append("<h1>").append(title).append("</h1>\n");
        if (!actions.isEmpty()) {
            indent(indent + 1).append("<div class=\"page-header__actions\">\n");
            for (Map<String, Object> act : actions) {
                String label = HtmlEscaper.escapeText(SfcBuildSupport.str(act.get("label")));
                String type = SfcBuildSupport.str(act.get("type"));
                String cls = "primary".equals(type) ? "btn btn--primary" : "btn";
                indent(indent + 2).append("<button type=\"button\" class=\"").append(cls).append("\">")
                        .append(label).append("</button>\n");
            }
            indent(indent + 1).append("</div>\n");
        }
        indent(indent).append("</header>\n");
    }

    private void renderSearchBar(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        List<Map<String, Object>> fields = SfcBuildSupport.listOfMaps(props.get("fields"));
        String formVar = "searchForm_" + SfcBuildSupport.safeJsId(node.getId());

        needReactive = true;
        scriptBody.append("// search form: ").append(node.getId()).append("\n");
        scriptBody.append("const ").append(formVar).append(" = reactive({\n");
        for (int i = 0; i < fields.size(); i++) {
            String name = SfcBuildSupport.str(fields.get(i).get("name"));
            if (name.isBlank()) {
                continue;
            }
            scriptBody.append("  ").append(name).append(": ''");
            if (i < fields.size() - 1) {
                scriptBody.append(",");
            }
            scriptBody.append("\n");
        }
        scriptBody.append("})\n\n");

        indent(indent).append("<form class=\"search-bar\" @submit.prevent>\n");
        for (Map<String, Object> field : fields) {
            String name = SfcBuildSupport.str(field.get("name"));
            String label = HtmlEscaper.escapeText(SfcBuildSupport.str(field.get("label")));
            String control = SfcBuildSupport.str(field.get("control"));
            indent(indent + 1).append("<div class=\"field\">\n");
            indent(indent + 2).append("<label>").append(label).append("</label>\n");
            if ("select".equals(control)) {
                indent(indent + 2).append("<select v-model=\"").append(formVar).append(".").append(name).append("\">\n");
                indent(indent + 3).append("<option value=\"\">请选择</option>\n");
                Object rawOpts = field.get("options");
                if (rawOpts instanceof List<?> list) {
                    for (Object opt : list) {
                        String optVal = HtmlEscaper.escapeAttr(SfcBuildSupport.str(opt));
                        String optText = HtmlEscaper.escapeText(SfcBuildSupport.str(opt));
                        indent(indent + 3).append("<option value=\"").append(optVal).append("\">")
                                .append(optText).append("</option>\n");
                    }
                }
                indent(indent + 2).append("</select>\n");
            } else {
                indent(indent + 2).append("<input type=\"text\" v-model=\"")
                        .append(formVar).append(".").append(name).append("\" />\n");
            }
            indent(indent + 1).append("</div>\n");
        }
        indent(indent + 1).append("<div class=\"field field--actions\">\n");
        indent(indent + 2).append("<button type=\"button\" class=\"btn btn--primary\">查询</button>\n");
        indent(indent + 2).append("<button type=\"button\" class=\"btn\">重置</button>\n");
        indent(indent + 1).append("</div>\n");
        indent(indent).append("</form>\n");
    }

    private void renderDataTable(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        List<Map<String, Object>> columns = SfcBuildSupport.listOfMaps(props.get("columns"));
        List<Map<String, Object>> rowActions = SfcBuildSupport.listOfMaps(props.get("rowActions"));
        String dataVar = "tableData_" + SfcBuildSupport.safeJsId(node.getId());

        scriptBody.append("// mock table data: ").append(node.getId()).append("\n");
        scriptBody.append("const ").append(dataVar).append(" = [\n  ");
        scriptBody.append(SfcBuildSupport.buildMockRowsJs(columns, mockSeed));
        scriptBody.append("\n]\n\n");

        indent(indent).append("<table class=\"data-table\">\n");
        indent(indent + 1).append("<thead>\n");
        indent(indent + 2).append("<tr>\n");
        for (Map<String, Object> col : columns) {
            String label = HtmlEscaper.escapeText(SfcBuildSupport.str(col.get("label")));
            indent(indent + 3).append("<th>").append(label).append("</th>\n");
        }
        if (!rowActions.isEmpty()) {
            indent(indent + 3).append("<th>操作</th>\n");
        }
        indent(indent + 2).append("</tr>\n");
        indent(indent + 1).append("</thead>\n");
        indent(indent + 1).append("<tbody>\n");
        indent(indent + 2).append("<tr v-for=\"(row, idx) in ").append(dataVar).append("\" :key=\"idx\">\n");
        for (Map<String, Object> col : columns) {
            String prop = SfcBuildSupport.str(col.get("prop"));
            indent(indent + 3).append("<td>{{ row.").append(prop).append(" }}</td>\n");
        }
        if (!rowActions.isEmpty()) {
            indent(indent + 3).append("<td>\n");
            for (Map<String, Object> act : rowActions) {
                String label = HtmlEscaper.escapeText(SfcBuildSupport.str(act.get("label")));
                indent(indent + 4).append("<button type=\"button\" class=\"btn btn--link\">")
                        .append(label).append("</button>\n");
            }
            indent(indent + 3).append("</td>\n");
        }
        indent(indent + 2).append("</tr>\n");
        indent(indent + 1).append("</tbody>\n");
        indent(indent).append("</table>\n");
    }

    private void renderPagination(DslNode node, int indent) {
        int pageSize = SfcBuildSupport.propInt(node.getProps(), "pageSize", 10);
        indent(indent).append("<nav class=\"pagination\" aria-label=\"pagination\">\n");
        indent(indent + 1).append("<span>共 3 条 · 每页 ").append(pageSize).append(" 条</span>\n");
        indent(indent + 1).append("<button type=\"button\" class=\"btn\" disabled>上一页</button>\n");
        indent(indent + 1).append("<span>1</span>\n");
        indent(indent + 1).append("<button type=\"button\" class=\"btn\" disabled>下一页</button>\n");
        indent(indent).append("</nav>\n");
    }

    private void renderFormSection(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        List<Map<String, Object>> fields = SfcBuildSupport.listOfMaps(props.get("fields"));
        String formVar = "form_" + SfcBuildSupport.safeJsId(node.getId());
        String submitFn = "onSubmit_" + SfcBuildSupport.safeJsId(node.getId());

        needReactive = true;
        scriptBody.append("// form model: ").append(node.getId()).append("\n");
        scriptBody.append("const ").append(formVar).append(" = reactive({\n");
        for (int i = 0; i < fields.size(); i++) {
            String name = SfcBuildSupport.str(fields.get(i).get("name"));
            if (name.isBlank()) {
                continue;
            }
            scriptBody.append("  ").append(name).append(": ''");
            if (i < fields.size() - 1) {
                scriptBody.append(",");
            }
            scriptBody.append("\n");
        }
        scriptBody.append("})\n\n");
        scriptBody.append("function ").append(submitFn).append("() {\n");
        scriptBody.append("  console.log('submit', ").append(formVar).append(")\n");
        scriptBody.append("}\n\n");
        scriptBody.append("const __lastFormSubmit = ").append(submitFn).append("\n\n");

        indent(indent).append("<form class=\"form-section\" @submit.prevent=\"").append(submitFn).append("\">\n");
        for (Map<String, Object> field : fields) {
            String name = SfcBuildSupport.str(field.get("name"));
            String label = HtmlEscaper.escapeText(SfcBuildSupport.str(field.get("label")));
            String control = SfcBuildSupport.str(field.get("control"));
            boolean required = Boolean.TRUE.equals(field.get("required"));
            boolean readonly = Boolean.TRUE.equals(field.get("readonly"));

            indent(indent + 1).append("<div class=\"field\">\n");
            indent(indent + 2).append("<label>");
            template.append(label);
            if (required) {
                template.append(" *");
            }
            template.append("</label>\n");
            if ("textarea".equals(control)) {
                indent(indent + 2).append("<textarea v-model=\"")
                        .append(formVar).append(".").append(name).append("\" rows=\"3\"");
                if (readonly) {
                    template.append(" readonly");
                }
                template.append("></textarea>\n");
            } else if ("select".equals(control)) {
                indent(indent + 2).append("<select v-model=\"")
                        .append(formVar).append(".").append(name).append("\"");
                if (readonly) {
                    template.append(" disabled");
                }
                template.append(">\n");
                indent(indent + 3).append("<option value=\"\">请选择</option>\n");
                Object rawOpts = field.get("options");
                if (rawOpts instanceof List<?> list) {
                    for (Object opt : list) {
                        String optVal = HtmlEscaper.escapeAttr(SfcBuildSupport.str(opt));
                        String optText = HtmlEscaper.escapeText(SfcBuildSupport.str(opt));
                        indent(indent + 3).append("<option value=\"").append(optVal).append("\">")
                                .append(optText).append("</option>\n");
                    }
                }
                indent(indent + 2).append("</select>\n");
            } else {
                indent(indent + 2).append("<input type=\"text\" v-model=\"")
                        .append(formVar).append(".").append(name).append("\"");
                if (readonly) {
                    template.append(" readonly");
                }
                template.append(" />\n");
            }
            indent(indent + 1).append("</div>\n");
        }
        indent(indent).append("</form>\n");
    }

    private void renderActionBar(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        List<Map<String, Object>> actions = SfcBuildSupport.listOfMaps(props.get("actions"));
        String handler = "onAction_" + SfcBuildSupport.safeJsId(node.getId());

        scriptBody.append("function ").append(handler).append("(actionId) {\n");
        scriptBody.append("  if (typeof __lastFormSubmit === 'function' && (actionId === 'act_submit' || actionId === 'submit')) {\n");
        scriptBody.append("    __lastFormSubmit()\n");
        scriptBody.append("    return\n");
        scriptBody.append("  }\n");
        scriptBody.append("  console.log('action', actionId)\n");
        scriptBody.append("}\n\n");

        indent(indent).append("<div class=\"action-bar\">\n");
        for (Map<String, Object> act : actions) {
            String id = SfcBuildSupport.str(act.get("id"));
            String label = HtmlEscaper.escapeText(SfcBuildSupport.str(act.get("label")));
            String type = SfcBuildSupport.str(act.get("type"));
            String cls = switch (type) {
                case "primary" -> "btn btn--primary";
                case "danger" -> "btn btn--danger";
                default -> "btn";
            };
            indent(indent + 1)
                    .append("<button type=\"button\" class=\"")
                    .append(cls)
                    .append("\" @click=\"")
                    .append(handler)
                    .append("(")
                    .append(SfcBuildSupport.jsString(id))
                    .append(")\">")
                    .append(label)
                    .append("</button>\n");
        }
        indent(indent).append("</div>\n");
    }

    private void renderStatCards(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        List<Map<String, Object>> items = SfcBuildSupport.listOfMaps(props.get("items"));

        indent(indent).append("<section class=\"stat-cards\">\n");
        for (Map<String, Object> item : items) {
            String label = HtmlEscaper.escapeText(SfcBuildSupport.str(item.get("label")));
            String value = HtmlEscaper.escapeText(SfcBuildSupport.str(item.get("value")));
            String unit = HtmlEscaper.escapeText(SfcBuildSupport.str(item.get("unit")));
            indent(indent + 1).append("<article class=\"stat-card\">\n");
            indent(indent + 2).append("<div class=\"stat-card__value\">").append(value);
            if (!unit.isBlank()) {
                template.append(unit);
            }
            template.append("</div>\n");
            indent(indent + 2).append("<div class=\"stat-card__label\">").append(label).append("</div>\n");
            indent(indent + 1).append("</article>\n");
        }
        indent(indent).append("</section>\n");
    }

    private void renderTextBlock(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        String content = HtmlEscaper.escapeText(SfcBuildSupport.propString(props, "content", ""));
        String variant = SfcBuildSupport.propString(props, "variant", "body");
        String cls = "hint".equals(variant) ? "text-block text-block--hint" : "text-block";
        indent(indent).append("<p class=\"").append(cls).append("\">").append(content).append("</p>\n");
    }

    private void renderContainer(DslNode node, int indent) {
        Map<String, Object> props = node.getProps();
        String layout = SfcBuildSupport.propString(props, "layout", "stack");
        if ("two-column".equals(layout)) {
            List<DslNode> left = SfcBuildSupport.asNodes(props.get("left"));
            List<DslNode> right = SfcBuildSupport.asNodes(props.get("right"));
            indent(indent).append("<div class=\"container-two-column\">\n");
            indent(indent + 1).append("<div class=\"container-col\">\n");
            for (DslNode child : left) {
                renderNode(child, indent + 2);
            }
            indent(indent + 1).append("</div>\n");
            indent(indent + 1).append("<div class=\"container-col\">\n");
            for (DslNode child : right) {
                renderNode(child, indent + 2);
            }
            indent(indent + 1).append("</div>\n");
            indent(indent).append("</div>\n");
        } else {
            indent(indent).append("<div class=\"container-stack\">\n");
            if (node.getChildren() != null) {
                for (DslNode child : node.getChildren()) {
                    renderNode(child, indent + 1);
                }
            }
            indent(indent).append("</div>\n");
        }
    }

    private StringBuilder indent(int level) {
        SfcBuildSupport.appendIndent(template, level);
        return template;
    }
}
